testproj/demo/urls.py
from django.urls import path

from demo.views import IndexView, ComputersView

app_name = "demo"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("computers/", ComputersView.as_view(), name="computers"),
]

testproj/testproj/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("demo.urls")),
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
]

testproj/demo/forms.py
from django import forms

from windows_auth.ldap import get_ldap_manager


class ComputerDescriptionForm(forms.Form):
    name = forms.CharField()
    description = forms.CharField()

    _reader = None

    def get_reader(self):
        if not self._reader:
            manager = get_ldap_manager("EXAMPLE")
            self._reader = manager.get_reader("computer", f"name: {self.data.get('name')}")

        return self._reader

    def is_valid(self):
        return len(self.get_reader().search()) > 0

testproj/demo/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, FormView
from ldap3 import Writer

from demo.forms import ComputerDescriptionForm
from windows_auth.decorators import ldap_sync_required, domain_required
from windows_auth.ldap import get_ldap_manager


class IndexView(TemplateView, LoginRequiredMixin):
    template_name = "demo/index.html"

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context["remote_user"] = self.request.META.get('REMOTE_USER')
        return context


@method_decorator(ldap_sync_required(raise_exception=True), name="dispatch")
# @method_decorator(domain_required(domain="NOTEXAMPLE", bypass_superuser=False), name="dispatch")
class ComputersView(FormView):
    template_name = "demo/computers.html"
    form_class = ComputerDescriptionForm
    success_url = reverse_lazy("demo:computers")

    def get_context_data(self, **kwargs):
        context = super(ComputersView, self).get_context_data(**kwargs)
        manager = get_ldap_manager("EXAMPLE")
        reader = manager.get_reader("computer", attributes=("name", "description"))
        context["computers"] = reader.search()
        return context

    def form_valid(self, form: ComputerDescriptionForm):
        # write new description
        reader = form.get_reader()
        writer = Writer.from_cursor(reader)
        computer = writer[0]
        computer.description = form.data["description"]
        writer.commit()
        return super(ComputersView, self).form_valid(form)

testproj/demo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>django-windowsauth Demo</title>
</head>
<body>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% block content %}
    {% endblock content %}
</body>
</html>

testproj/demo/templates/demo/computers.html
{% extends "base.html" %}
{% block content %}
    <a href="{% url 'demo:index' %}">Go home</a>
    <ul>
        {% for computer in computers %}
            <li>{{ computer.name }} - {{ computer.description | default:"Empty" }}
                <form method="post">
                    {% csrf_token %}
                    <input name="name" value="{{ computer.name }}" hidden>
                    {{ form.description }}
                    <input type="submit" value="Submit">
                </form>
            </li>
        {% empty %}
            <li>No computers found</li>
        {% endfor %}
    </ul>
{% endblock content %}

testproj/demo/templates/demo/index.html
{% extends "base.html" %}
{% block content %}
    <h1>Hello {{ user }}!</h1>
    <a href="{% url 'demo:computers' %}">See computers</a>
{% endblock content %}